# PBS/SLURM configuration

# If submitting to a different project to your default, uncomment line below
# and replace PROJECT_CODE with appropriate code. This may require setting shortpath
# project: PROJECT_CODE

# Force payu to always find, and save, files in this scratch project directory
# shortpath: /scratch/PROJECT_CODE

scheduler: slurm
#queue: do not set for slurm
walltime: 03:00:00
jobname: 1deg_jra55_ryf
mem: 200G
#account: sail 
partition: rack1
#project: do not set for slurm, creates separate folder 
ncpus: 380
nnodes: 5
#npernode: 112
#pmix: pmix_v3



#modules:
  # use:
  #     - /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/modules/linux-rhel8-x86_64
#  load:
      # - access-om2
      # - compiler/latest
      # - mpi/2021.12
      #- intel-oneapi-compilers/2021.2.0-p7vtyvv
      #-  netcdf-c/4.7.4-d4klyvu 
      #- netcdf-fortran/4.5.2-5ln2rw
      #- parallelio/2.5.2-fmgl254 
      #- openmpi/4.1.4-ga6avsd
      #- pmix@4.2.2

# Model configuration
name: common
model: access-om2
input:
  - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/JRA55_MOM1_conserve2nd.nc
  - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/JRA55_MOM1_patch.nc
  - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/rmp_jra55_cice_1st_conserve.nc
  - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/rmp_jra55_cice_2nd_conserve.nc
  - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/rmp_jra55_cice_patch.nc
submodels:
    - name: atmosphere
      model: yatm
      exe: yatm.exe
      input:
            - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/rmp_jrar_to_cict_CONSERV.nc
            - /storage/ekman/tilinina/ACCESS-OM2/make_ryf
      ncpus: 1
      nnodes: 1
      npernode: 1
      partition: rack1
      #mem: 200GB

      

    - name: ocean
      model: mom
      exe: mom5_access_om
      input:
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/grids/mosaic/global.1deg/2020.05.30/grid_spec.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/grids/mosaic/global.1deg/2020.05.30/ocean_hgrid.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/grids/mosaic/global.1deg/2020.05.30/ocean_mosaic.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/grids/bathymetry/global.1deg/2020.10.22/topog.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/grids/bathymetry/global.1deg/2020.10.22/ocean_mask.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/grids/vertical/global.1deg/2020.10.22/ocean_vgrid.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/processor_masks/global.1deg/216.16x15/2020.05.30/ocean_mask_table
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/chlorophyll/global.1deg/2020.05.30/chl.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/initial_conditions/global.1deg/2020.10.22/ocean_temp_salt.res.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/tides/global.1deg/2020.05.30/tideamp.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/tides/global.1deg/2020.05.30/roughness_amp.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/tides/global.1deg/2020.05.30/roughness_cdbot.nc
          - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ocean/surface_salt_restoring/global.1deg/2020.05.30/salt_sfc_restore.nc
      ncpus: 228
      nnodes: 3
      npernode: 76  
      partition: rack1
      #mem: 200GB



    - name: ice
      model: cice5
      exe: cice_auscom_360x300_24x1_24p.exe
      input:
        - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ice/grids/global.1deg/2020.05.30/grid.nc
        - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ice/grids/global.1deg/2020.10.22/kmt.nc
        - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ice/initial_conditions/global.1deg/2020.05.30/i2o.nc
        - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ice/initial_conditions/global.1deg/2020.05.30/o2i.nc
        - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ice/initial_conditions/global.1deg/2020.05.30/u_star.nc
        - /storage/ekman/tilinina/ACCESS-OM2/INPUT/access-om2/ice/initial_conditions/global.1deg/2020.05.30/monthly_sstsss.nc
      nnodes: 1
      npernode: 76
      ncpus: 76    
      #npernode: 24
      #ncpus: 24  
      partition: rack1
     #mem: 200GB
     

# Collation
collate:
  restart: True
  walltime: 01:00:00
  mem: 30G
  ncpus: 4
  nnodes: 1
  npernode: 4
  partition: rack1
#  queue: normal
  exe: mppnccombine

# # Sync options for automatically copying data from ephemeral scratch space to 
# # longer term storage
# sync:
#     enable: False # set path below and change to true
#     #path: null # Set to location on /g/data or a remote server and path (rsync syntax)
#     path: /storage/ekman/tilinina/ACCESS-OM2/experiment/1deg_jra55_ryf
#     restarts: True 
#     exclude_uncollated: False
#     #remove_local_files: True
#     #remove_local_dirs: True
#     mem: 2G
#     ncpus: 4
#     nnodes: 1
#     npernode: 4

# Miscls
runlog: true
stacksize: unlimited

restart_freq: 5YS
experiment: 1deg_jra55_ryf_5yr
laboratory: /storage/ekman/tilinina/ACCESS-OM2/experiment/1deg_jra55_ryf

#mpirun: --mca io ompio --mca io_ompio_num_aggregators 1 
#mpirun: --mca btl_tcp_if_exclude virbr0,lo
mpi:
  runcmd: srun
# #qsub_flags: -W umask=027
# qsub_flags: umask 027
# env:
#     UCX_LOG_LEVEL: 'error'
#     LD_LIBRARY_PATH: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/openmpi-4.1.4-ga6avsdxmjya35twagfjts7jp3yahbwt/lib:$LD_LIBRARY_PATH
#     OMPI_MCA_btl_tcp_if_includel: ib0
#     MCA_IO: ompio 
#     MCA_IO_OMPIO_NUM_AGGREGATORS: 1
manifest:
  reproduce:
    exe: False

# set number of cores per node (28 for normalbw, 48 for normal on gadi), 
platform:
    nodesize: 76

# sweep and resubmit on specific errors - see https://github.com/payu-org/payu/issues/241#issuecomment-610739771
userscripts:
    error: tools/resub.sh
    run: rm -f resubmit.count
    sync: /storage/ekman/tilinina/ACCESS-OM2/om2-scripts/concatenate_ice/concat_ice_daily.sh
 
