# PBS/SLURM configuration

# If submitting to a different project to your default, uncomment line below
# and replace PROJECT_CODE with appropriate code. This may require setting shortpath
# project: PROJECT_CODE

# Force payu to always find, and save, files in this scratch project directory
# shortpath: /scratch/PROJECT_CODE

scheduler: slurm
#queue: do not set for slurm
walltime: 09:00:00
jobname: 1deg_jra55_ryf
mem: 1000G
account: ICT25_MHPC 
partition: dcgp_usr_prod
#project: do not set for slurm, creates separate folder 
ncpus: 560
nnodes: 5
npernode: 112
#pmix: pmix_v3



modules:
  use:
      - /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/modules/linux-rhel8-x86_64
  load:
      - access-om2/access-om2-o33figh
      - intel-oneapi-compilers/2021.2.0-p7vtyvv
      - netcdf-c/4.7.4-d4klyvu 
      - netcdf-fortran/4.5.2-5ln2rw
      - parallelio/2.5.2-fmgl254 
      - openmpi/4.1.4-ga6avsd
      - pmix@4.2.2
# Sync options for automatically copying data from ephemeral scratch space to 
# longer term storage
sync:
    enable: False # set path below and change to true
    path: null # Set to location on /g/data or a remote server and path (rsync syntax)

# Model configuration
name: common
model: access-om2
input:
  - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/JRA55_MOM1_conserve2nd.nc
  - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/JRA55_MOM1_patch.nc
  - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/rmp_jra55_cice_1st_conserve.nc
  - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/rmp_jra55_cice_2nd_conserve.nc
  - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/rmp_jra55_cice_patch.nc
submodels:
    - name: atmosphere
      model: yatm
      exe: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/libaccessom2-access-om2-lnlbi4d7tcxgoecguezpvjwbg6jkehzc/bin/yatm.exe
      input:
            - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/remapping_weights/JRA55/global.1deg/2020.05.30/rmp_jrar_to_cict_CONSERV.nc
            - /leonardo/home/userexternal/ntilinin/make_ryf
      ncpus: 1
      nnodes: 1
      npernode: 1
      partition: dcgp_usr_prod
      mem: 1000GB

      

    - name: ocean
      model: mom
      exe: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/mom5-access-om2-ogthsyx7h5fri5tww7aukcs6ifizlxwm/bin/fms_ACCESS-OM.x
      input:
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/mosaic/global.1deg/2020.05.30/grid_spec.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/mosaic/global.1deg/2020.05.30/ocean_hgrid.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/mosaic/global.1deg/2020.05.30/ocean_mosaic.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/bathymetry/global.1deg/2020.10.22/topog.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/bathymetry/global.1deg/2020.10.22/ocean_mask.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/grids/vertical/global.1deg/2020.10.22/ocean_vgrid.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/processor_masks/global.1deg/216.16x15/2020.05.30/ocean_mask_table
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/chlorophyll/global.1deg/2020.05.30/chl.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/initial_conditions/global.1deg/2020.10.22/ocean_temp_salt.res.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/tides/global.1deg/2020.05.30/tideamp.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/tides/global.1deg/2020.05.30/roughness_amp.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/tides/global.1deg/2020.05.30/roughness_cdbot.nc
          - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ocean/surface_salt_restoring/global.1deg/2020.05.30/salt_sfc_restore.nc
      ncpus: 240
      nnodes: 3
      npernode: 112  
      partition: dcgp_usr_prod
      mem: 1000GB



    - name: ice
      model: cice5
      exe: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/cice5-access-om2-woizzl5sdrgejgmrvayt7gax5gmrxxgj/bin/cice_auscom_360x300_24x1_24p.exe
      input:
        - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ice/grids/global.1deg/2020.05.30/grid.nc
        - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ice/grids/global.1deg/2020.10.22/kmt.nc
        - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ice/initial_conditions/global.1deg/2020.05.30/i2o.nc
        - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ice/initial_conditions/global.1deg/2020.05.30/o2i.nc
        - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ice/initial_conditions/global.1deg/2020.05.30/u_star.nc
        - /leonardo_scratch/fast/ICT24_MHPC/ntilinin/INPUT/access-om2/ice/initial_conditions/global.1deg/2020.05.30/monthly_sstsss.nc
      ncpus: 112
      nnodes: 1
      npernode: 112  
      partition: dcgp_usr_prod
      mem: 1000GB
     

# Collation
collate:
  restart: true
  walltime: 1-00:00:00
  mem: 30GB
  ncpus: 4
  nnodes: 1
  npernode: 112
  partition: dcgp_usr_prod

#  queue: normal
  exe: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/mom5-access-om2-ogthsyx7h5fri5tww7aukcs6ifizlxwm/bin/mppnccombine.spack

# Misc
runlog: true
stacksize: unlimited
restart_freq: 5YS
mpirun: --mca io ompio --mca io_ompio_num_aggregators 1 
#mpirun: --mca btl_tcp_if_exclude virbr0,lo
#mpirun: 
mpi:
  runcmd: srun
qsub_flags: -W umask=027
env:
    UCX_LOG_LEVEL: 'error'

manifest:
  reproduce:
    exe: False

# set number of cores per node (28 for normalbw, 48 for normal on gadi), 
platform:
    nodesize: 112

# sweep and resubmit on specific errors - see https://github.com/payu-org/payu/issues/241#issuecomment-610739771
userscripts:
    error: tools/resub.sh
    run: rm -f resubmit.count
    sync: /leonardo/home/userexternal/ntilinin/om2-scripts/concatenate_ice/concat_ice_daily.sh
 