format: yamanifest
version: 1.0
---
work/atmosphere/yatm.exe:
  fullpath: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/libaccessom2-access-om2-lnlbi4d7tcxgoecguezpvjwbg6jkehzc/bin/yatm.exe
  hashes:
    binhash: e1d6d7386c947ed3e4e02778874c8e87
    md5: 059240725851f88b088b1093b72a69d7
work/ice/cice_auscom_360x300_24x1_24p.exe:
  fullpath: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/cice5-access-om2-woizzl5sdrgejgmrvayt7gax5gmrxxgj/bin/cice_auscom_360x300_24x1_24p.exe
  hashes:
    binhash: f143a0a434f0857196190016b92f4435
    md5: 54f245f6c2e9a1787dca0a2daa4645f2
work/ocean/fms_ACCESS-OM.x:
  fullpath: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/mom5-access-om2-ogthsyx7h5fri5tww7aukcs6ifizlxwm/bin/fms_ACCESS-OM.x
  hashes:
    binhash: 60231fd32f5bed43dce546f291ac8786
    md5: 9872eb76cbad6bd12889c91ac9ad41a9
