format: yamanifest
version: 1.0
---
work/atmosphere/yatm.exe:
  fullpath: /leonardo_scratch/large/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/libaccessom2-master-tqkpbd6z5fimuedszsnqmd3w627x7elu/bin/yatm.exe
  hashes:
    binhash: fc67869550b18c20fc713656daf618a7
    md5: 1eae575432e642d60e006fc68bfcadcf
work/ice/cice_auscom_360x300_24x1_24p.exe:
  fullpath: /leonardo_scratch/large/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/cice5-master-2cqzrfobwphbj27loirf6plzpbrbtlmn/bin/cice_auscom_360x300_24x1_24p.exe
  hashes:
    binhash: b324b868c4709a306f9f43906557319a
    md5: 8d092e7212e3b99aa389be5d740484ef
work/ocean/fms_ACCESS-OM.x:
  fullpath: /leonardo_scratch/large/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/mom5-master-xpemflbdqur3nlgvx64dq4635vpq65yz/bin/fms_ACCESS-OM.x
  hashes:
    binhash: 8064017dd1ef1e1b173b7d72ad86797a
    md5: 5ffac37f530a8b984899cbb46f561d4b
