format: yamanifest
version: 1.0
---
work/atmosphere/yatm.exe:
  fullpath: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/libaccessom2-access-om2-shkjnrowt2akfatdybsizrujxwfnam7f/bin/yatm.exe
  hashes:
    binhash: 790ca3fb9d0239e684364edbae60a5dc
    md5: bc282b8362d6e054290c33949c343f46
work/ice/cice_auscom_360x300_24x1_24p.exe:
  fullpath: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/cice5-access-om2-ibzshgj256fxgkuxkqavttdzq3txzc7h/bin/cice_auscom_360x300_24x1_24p.exe
  hashes:
    binhash: ac5c2da65f9b5dd48d0a3cd9ee77a1fc
    md5: 562e557a4e3f35180d7f3d38836d6e71
work/ocean/fms_ACCESS-OM.x:
  fullpath: /leonardo/home/userexternal/ntilinin/ACCESS-NRI/release/linux-rhel8-x86_64/intel-2021.2.0/mom5-access-om2-bkjgbganje2ypawu2td25fk5eyfwi3ea/bin/fms_ACCESS-OM.x
  hashes:
    binhash: 6f9a15e81284de6c7395ab71bcb0353b
    md5: de5bd8ec43adad37e155e972d5d6d4d0
